// Comprehensive field mapping configuration for all models
export const MODEL_FIELD_MAPPINGS: Record<
  string,
  {
    allowedFields: string[];
    requiredDefaults?: Record<string, any>;
    fieldMappings?: Record<string, string>;
  }
> = {
  state: {
    allowedFields: ["stateName", "abbreviation", "population", "createdAt", "updatedAt"],
    fieldMappings: { state_name: "stateName" },
  },
  county: {
    allowedFields: ["countyName", "population", "stateId", "createdAt", "updatedAt"],
    requiredDefaults: { stateId: 1 },
    fieldMappings: { county_name: "countyName" },
  },
  city: {
    allowedFields: ["cityName", "population", "countyId", "createdAt", "updatedAt"],
    requiredDefaults: { countyId: 1 },
    fieldMappings: { city_name: "cityName" },
  },
  zipCode: {
    allowedFields: ["zipCode", "cityId", "createdAt", "updatedAt"],
    requiredDefaults: { cityId: 1 },
    fieldMappings: { zip_code: "zipCode" },
  },
  stateRegion: {
    allowedFields: [
      "regionName",
      "regionCode",
      "description",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: { region_name: "regionName", region_code: "regionCode", is_active: "isActive" },
  },
  tableRegistry: {
    allowedFields: [
      "tableName",
      "shardKeyColumn",
      "maxRecordsPerShard",
      "currentActiveShards",
      "autoScalingEnabled",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      shardKeyColumn: "id",
      maxRecordsPerShard: 10000,
      currentActiveShards: 1,
      autoScalingEnabled: false,
    },
    fieldMappings: {
      table_name: "tableName",
      shard_key: "shardKeyColumn",
      is_active: "autoScalingEnabled",
    },
  },
  tableShardRegistry: {
    allowedFields: [
      "tableRegistryId",
      "shardNumber",
      "stateRegionId",
      "currentRecordCount",
      "status",
      "databaseServer",
      "lastMaintenance",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { tableRegistryId: 1, stateRegionId: 1 },
    fieldMappings: {
      table_registry_id: "tableRegistryId",
      shard_number: "shardNumber",
      region_id: "stateRegionId",
      server_name: "databaseServer",
    },
  },
  person: {
    allowedFields: [
      "prefix",
      "firstName",
      "middleName",
      "lastName",
      "suffix",
      "dateOfBirth",
      "gender",
      "juvenile",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { firstName: "Unknown", lastName: "Unknown" },
    fieldMappings: {
      first_name: "firstName",
      middle_name: "middleName",
      last_name: "lastName",
      date_of_birth: "dateOfBirth",
    },
  },
  governmentEntity: {
    allowedFields: [
      "entityName",
      "governmentLevelId",
      "stateId",
      "countyId",
      "cityId",
      "locationId",
      "latitude",
      "longitude",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { entityName: "Unknown Entity", governmentLevelId: 1 },
    fieldMappings: {
      entity_name: "entityName",
      government_level_id: "governmentLevelId",
    },
  },
  business: {
    allowedFields: [
      "name",
      "chiefExecutiveId",
      "businessLicenseNumber",
      "businessLicenseStatusId",
      "businessLicenseExpirationDate",
      "businessTypeId",
      "serviceCategoryId",
      "employeeCountRangeId",
      "annualRevenueRangeId",
      "minorityOwnedBusiness",
      "womenOwnedBusiness",
      "veteranOwnedBusiness",
      "website",
      "locationId",
      "stateId",
      "countyId",
      "cityId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { name: "Unknown Business", stateRegionId: 1 },
    fieldMappings: {
      business_name: "name",
      website_url: "website",
      tax_id: "businessLicenseNumber",
    },
  },
  nonGovernmentalOrganizationShard1: {
    allowedFields: [
      "employerIdentificationNumber",
      "name",
      "principalOfficerId",
      "ngoType",
      "guidestarProfilePageUrl",
      "locationId",
      "ngoWebsiteUrl",
      "stateId",
      "countyId",
      "cityId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      name: "Unknown NGO",
      stateRegionId: 1,
      employerIdentificationNumber: "Unknown",
    },
    fieldMappings: {
      organization_name: "name",
      ein: "employerIdentificationNumber",
      website_url: "ngoWebsiteUrl",
    },
  },
  governmentLevel: {
    allowedFields: ["levelName", "hierarchyOrder", "description", "createdAt", "updatedAt"],
    requiredDefaults: { levelName: "Unknown Level", hierarchyOrder: 1 },
    fieldMappings: { level_name: "levelName", hierarchy_order: "hierarchyOrder" },
  },
  organizationType: {
    allowedFields: ["typeName", "description", "createdAt", "updatedAt"],
    requiredDefaults: { typeName: "Unknown Type" },
    fieldMappings: { type_name: "typeName" },
  },
  relationshipType: {
    allowedFields: [
      "relationshipName",
      "description",
      "isEmployment",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { relationshipName: "Unknown Relationship" },
    fieldMappings: {
      relationship_name: "relationshipName",
      is_employment: "isEmployment",
      is_active: "isActive",
    },
  },
  reviewType: {
    allowedFields: [
      "typeName",
      "description",
      "requiresResponse",
      "priorityLevel",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { typeName: "Unknown Review Type" },
    fieldMappings: {
      type_name: "typeName",
      requires_response: "requiresResponse",
      priority_level: "priorityLevel",
      is_active: "isActive",
    },
  },
  locationType: {
    allowedFields: ["locationType", "createdAt", "updatedAt"],
    requiredDefaults: { locationType: "Unknown Location Type" },
  },
  educationLevel: {
    allowedFields: ["id", "levelName", "levelCategory", "createdAt", "updatedAt"],
    requiredDefaults: { levelName: "Unknown Education Level" },
    fieldMappings: {
      level_name: "levelName",
      level_category: "levelCategory",
    },
  },
  licenseType: {
    allowedFields: ["typeName", "description", "category", "isActive", "createdAt", "updatedAt"],
    requiredDefaults: { typeName: "Unknown License Type" },
    fieldMappings: { license_name: "typeName" },
  },
  infractionType: {
    allowedFields: ["typeName", "description", "severity", "isActive", "createdAt", "updatedAt"],
    requiredDefaults: { typeName: "Unknown Infraction Type" },
    fieldMappings: { infraction_name: "typeName", severity_level: "severity" },
  },
  classification: {
    allowedFields: [
      "classificationName",
      "classificationType",
      "description",
      "stateId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { classificationName: "Unknown Classification" },
    fieldMappings: {
      classification_name: "classificationName",
      classification_type: "classificationType",
    },
  },
  statute: {
    allowedFields: [
      "statuteNumber",
      "title",
      "effectiveDate",
      "repealedDate",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { title: "Unknown Title" },
    fieldMappings: {
      statute_number: "statuteNumber",
      effective_date: "effectiveDate",
      repealed_date: "repealedDate",
    },
  },
  crime: {
    allowedFields: [
      "crimeName",
      "description",
      "classificationId",
      "severityLevel",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { crimeName: "Unknown Crime", classificationId: 1 },
    fieldMappings: { crime_name: "crimeName", severity_level: "severityLevel" },
  },
  element: {
    allowedFields: ["elementName", "description", "category", "isActive", "createdAt", "updatedAt"],
    requiredDefaults: { elementName: "Unknown Element" },
    fieldMappings: { element_name: "elementName", element_type: "category" },
  },
  punishment: {
    allowedFields: [
      "punishmentType",
      "description",
      "minPenalty",
      "maxPenalty",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { punishmentType: "Unknown Punishment" },
    fieldMappings: {
      punishment_type: "punishmentType",
      min_penalty: "minPenalty",
      max_penalty: "maxPenalty",
    },
  },
  crimeStatute: {
    allowedFields: [
      "crimeId",
      "statuteCode",
      "description",
      "penalty",
      "stateId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { crimeId: 1, statuteCode: "Unknown Code" },
  },
  offenseElement: {
    allowedFields: ["crimeId", "elementId", "isRequired", "createdAt", "updatedAt"],
    requiredDefaults: { crimeId: 1, elementId: 1 },
  },
  punishmentCrime: {
    allowedFields: ["punishmentId", "crimeId", "createdAt", "updatedAt"],
    requiredDefaults: { punishmentId: 1, crimeId: 1 },
  },
  stateReviewShard1: {
    allowedFields: [
      "governmentEntityId",
      "stateId",
      "reviewTypeId",
      "reviewText",
      "rating",
      "reviewerName",
      "reviewerEmail",
      "isVerified",
      "status",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      governmentEntityId: 1,
      stateId: 1,
      reviewTypeId: 1,
      reviewText: "No review text",
      stateRegionId: 1,
    },
    fieldMappings: {
      review_type_id: "reviewTypeId",
      content: "reviewText",
      subject_government_entity_id: "governmentEntityId",
      state_id: "stateId",
      reviewer_name: "reviewerName",
      reviewer_email: "reviewerEmail",
    },
  },
  countyReviewShard1: {
    allowedFields: [
      "governmentEntityId",
      "countyId",
      "reviewTypeId",
      "reviewText",
      "rating",
      "reviewerName",
      "reviewerEmail",
      "isVerified",
      "status",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      governmentEntityId: 1,
      countyId: 1,
      reviewTypeId: 1,
      reviewText: "No review text",
      stateRegionId: 1,
    },
    fieldMappings: {
      review_type_id: "reviewTypeId",
      content: "reviewText",
      subject_government_entity_id: "governmentEntityId",
      county_id: "countyId",
      reviewer_name: "reviewerName",
      reviewer_email: "reviewerEmail",
    },
  },
  cityReviewShard1: {
    allowedFields: [
      "governmentEntityId",
      "cityId",
      "reviewTypeId",
      "reviewText",
      "rating",
      "reviewerName",
      "reviewerEmail",
      "isVerified",
      "status",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      governmentEntityId: 1,
      cityId: 1,
      reviewTypeId: 1,
      reviewText: "No review text",
      stateRegionId: 1,
    },
    fieldMappings: {
      review_type_id: "reviewTypeId",
      content: "reviewText",
      subject_government_entity_id: "governmentEntityId",
      city_id: "cityId",
      reviewer_name: "reviewerName",
      reviewer_email: "reviewerEmail",
    },
  },
  crimeReportIncidentShard1: {
    allowedFields: [
      "crimeId",
      "incidentDate",
      "location",
      "description",
      "reportedBy",
      "status",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      crimeId: 1,
      incidentDate: new Date(),
      stateRegionId: 1,
      reportedBy: "Unknown Reporter",
    },
    fieldMappings: {
      crime_id: "crimeId",
      incident_date_time: "incidentDate",
    },
  },
  employmentDataShard1: {
    allowedFields: [
      "personId",
      "employerId",
      "jobTitle",
      "startDate",
      "endDate",
      "salary",
      "employmentType",
      "statusId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { personId: 1, stateRegionId: 1 },
    fieldMappings: { employment_status: "status" },
  },
  laborForceStatistics: {
    allowedFields: [
      "stateId",
      "countyId",
      "cityId",
      "year",
      "month",
      "laborForce",
      "employed",
      "unemployed",
      "unemploymentRate",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { year: 2024, month: 1 },
    fieldMappings: {
      total_labor_force: "laborForce",
      unemployed_count: "unemployed",
    },
  },
  populationHistory: {
    allowedFields: ["cityId", "year", "populationCount"],
    requiredDefaults: { year: 2024, populationCount: 0 },
    fieldMappings: { population_count: "populationCount" },
  },
  homelessCountData: {
    allowedFields: [
      "stateId",
      "countyId",
      "cityId",
      "year",
      "totalCount",
      "shelteredCount",
      "unshelteredCount",
      "familiesCount",
      "individualsCount",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { year: 2024, totalCount: 0 },
    fieldMappings: {
      total_homeless: "totalCount",
    },
  },
  housingStatusShard1: {
    allowedFields: [
      "personId",
      "housingType",
      "ownershipStatus",
      "monthlyRent",
      "monthlyMortgage",
      "moveInDate",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { personId: 1, housingType: "Unknown", stateRegionId: 1 },
    fieldMappings: { housing_status: "housingType" },
  },
  businessLicenseShard1: {
    allowedFields: [
      "businessId",
      "licenseNumber",
      "licenseType",
      "issueDate",
      "expirationDate",
      "statusId",
      "issuingAuthority",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      businessId: 1,
      licenseNumber: "Unknown",
      licenseType: "Unknown",
      issueDate: new Date(),
      stateRegionId: 1,
    },
    fieldMappings: {
      issue_date: "issueDate",
      license_id: "id",
      license_number: "licenseNumber",
      license_type: "licenseType",
      expiration_date: "expirationDate",
      issuing_authority: "issuingAuthority",
    },
  },
  businessSizeData: {
    allowedFields: [
      "stateId",
      "countyId",
      "cityId",
      "year",
      "sizeCategory",
      "businessCount",
      "employeeCount",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { year: 2024, sizeCategory: "Unknown", businessCount: 0 },
    fieldMappings: {
      size_category: "sizeCategory",
      business_count: "businessCount",
      employee_count: "employeeCount",
    },
  },
  graduationData: {
    allowedFields: [
      "stateId",
      "countyId",
      "cityId",
      "schoolYear",
      "graduationRate",
      "totalStudents",
      "graduatedStudents",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { schoolYear: "2023-2024" },
    fieldMappings: {
      school_year: "schoolYear",
      total_seniors: "totalStudents",
      graduates: "graduatedStudents",
    },
  },
  educationDataShard1: {
    allowedFields: [
      "personId",
      "educationLevelId",
      "institutionName",
      "graduationDate",
      "gpa",
      "major",
      "degree",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { personId: 1, educationLevelId: 1, stateRegionId: 1 },
    fieldMappings: { education_level: "institutionName" },
  },
  gradeProgressionShard1: {
    allowedFields: [
      "studentId",
      "fromGrade",
      "toGrade",
      "schoolYear",
      "promoted",
      "reason",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      studentId: 1,
      fromGrade: "Unknown",
      toGrade: "Unknown",
      schoolYear: "2023-2024",
      stateRegionId: 1,
    },
    fieldMappings: {
      student_id: "studentId",
      school_year: "schoolYear",
    },
  },
  disciplinaryActionShard1: {
    allowedFields: [
      "studentId",
      "actionType",
      "reason",
      "actionDate",
      "duration",
      "description",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      studentId: 1,
      actionType: "Unknown",
      actionDate: new Date(),
      stateRegionId: 1,
      duration: "Unknown",
    },
    fieldMappings: {
      student_id: "studentId",
      action_date: "actionDate",
      punishment_type: "actionType",
    },
  },
  teacherCredentialShard1: {
    allowedFields: [
      "teacherId",
      "credentialType",
      "subject",
      "issueDate",
      "expirationDate",
      "issuingAuthority",
      "statusId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      teacherId: 1,
      credentialType: "Unknown",
      issueDate: new Date(),
      stateRegionId: 1,
    },
    fieldMappings: {
      teacher_id: "teacherId",
      issue_date: "issueDate",
      expiration_date: "expirationDate",
      credential_type: "credentialType",
      issuing_authority: "issuingAuthority",
    },
  },
  classShard1: {
    allowedFields: [
      "id",
      "className",
      "subject",
      "educationLevelId",
      "teacherId",
      "capacity",
      "schedule",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { className: "Unknown Class", educationLevelId: 1, stateRegionId: 1 },
    fieldMappings: {
      class_name: "className",
      subject_area: "subject",
      teacher_id: "teacherId",
      max_enrollment: "capacity",
      school_year: "schedule",
    },
  },
  classEnrollmentShard1: {
    allowedFields: [
      "classId",
      "studentId",
      "enrollmentDate",
      "grade",
      "statusId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { classId: 1, studentId: 1, enrollmentDate: new Date(), stateRegionId: 1 },
    fieldMappings: {
      class_id: "classId",
      student_id: "studentId",
      enrollment_date: "enrollmentDate",
      completion_status: "status",
    },
  },
  personLocationShard1: {
    allowedFields: [
      "personId",
      "locationId",
      "relationshipType",
      "startDate",
      "endDate",
      "isPrimary",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { personId: 1, locationId: 1, relationshipType: "Unknown", stateRegionId: 1 },
    fieldMappings: {
      person_id: "personId",
      location_id: "locationId",
      location_start_date: "startDate",
      location_end_date: "endDate",
    },
  },
  organizationLocationShard1: {
    allowedFields: [
      "organizationId",
      "locationId",
      "relationshipType",
      "startDate",
      "endDate",
      "isPrimary",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      organizationId: 1,
      locationId: 1,
      relationshipType: "Unknown",
      stateRegionId: 1,
    },
    fieldMappings: {
      organization_id: "organizationId",
      location_id: "locationId",
      location_start_date: "startDate",
      location_end_date: "endDate",
    },
  },
  personOrgRelationshipShard1: {
    allowedFields: [
      "personId",
      "organizationId",
      "relationshipTypeId",
      "startDate",
      "endDate",
      "title",
      "salary",
      "statusId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      personId: 1,
      organizationId: 1,
      relationshipTypeId: 1,
      statusId: 1,
      stateRegionId: 1,
    },
    fieldMappings: {
      person_id: "personId",
      organization_id: "organizationId",
      relationship_type_id: "relationshipTypeId",
      relationship_start_date: "startDate",
      relationship_end_date: "endDate",
      status_id: "statusId",
    },
  },
  locationShard1: {
    allowedFields: [
      "id",
      "streetAddress1",
      "streetAddress2",
      "locationTypeId",
      "zipCodeId",
      "stateRegionId",
      "latitude",
      "longitude",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      streetAddress1: "Unknown Address",
      locationTypeId: 1,
      zipCodeId: 1,
      stateRegionId: 1,
    },
    fieldMappings: {
      address_line1: "streetAddress1",
      address_line2: "streetAddress2",
      location_type_id: "locationTypeId",
      zip_code_id: "zipCodeId",
      region_id: "stateRegionId",
    },
  },
  // Review Subject Association Models
  stateReviewSubjectShard1: {
    allowedFields: ["id", "subjectId", "reviewId", "createdAt", "updatedAt"],
    requiredDefaults: { subjectId: 1, reviewId: 1 },
  },
  countyReviewSubjectShard1: {
    allowedFields: ["id", "subjectId", "reviewId", "createdAt", "updatedAt"],
    requiredDefaults: { subjectId: 1, reviewId: 1 },
  },
  cityReviewSubjectShard1: {
    allowedFields: ["id", "subjectId", "reviewId", "createdAt", "updatedAt"],
    requiredDefaults: { subjectId: 1, reviewId: 1 },
  },
  // Education Infrastructure Models
  teachingCredential: {
    allowedFields: [
      "id",
      "credentialName",
      "credentialType",
      "issuingAuthority",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      credentialName: "Unknown Credential",
      credentialType: "Unknown Type",
      issuingAuthority: "Unknown Authority",
    },
  },
  schoolDistrict: {
    allowedFields: ["id", "districtId", "districtName", "cityId", "createdAt", "updatedAt"],
    requiredDefaults: { districtId: 1, districtName: "Unknown District", cityId: 1 },
  },
  school: {
    allowedFields: [
      "id",
      "schoolId",
      "schoolName",
      "districtId",
      "schoolType",
      "cityId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      schoolId: 1,
      schoolName: "Unknown School",
      districtId: 1,
      schoolType: "Unknown Type",
      cityId: 1,
      stateRegionId: 1,
    },
  },
  studentShard1: {
    allowedFields: [
      "id",
      "studentId",
      "personId",
      "schoolId",
      "currentGradeLevel",
      "enrollmentDate",
      "graduationDate",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      studentId: 1,
      personId: 1,
      schoolId: 1,
      currentGradeLevel: "Unknown Grade",
      stateRegionId: 1,
    },
  },
  schoolEmergencyIncidentShard1: {
    allowedFields: [
      "id",
      "incidentId",
      "schoolId",
      "incidentDate",
      "incidentType",
      "responseTimeMinutes",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      incidentId: 1,
      schoolId: 1,
      incidentType: "Unknown Incident",
      responseTimeMinutes: 0,
      stateRegionId: 1,
    },
  },
  studentArrestShard1: {
    allowedFields: [
      "id",
      "arrestId",
      "studentId",
      "personId",
      "crimeId",
      "statuteId",
      "classificationId",
      "arrestDate",
      "gradeLevel",
      "schoolId",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      arrestId: 1,
      studentId: 1,
      personId: 1,
      crimeId: 1,
      statuteId: 1,
      classificationId: 1,
      gradeLevel: "Unknown Grade",
      schoolId: 1,
      stateRegionId: 1,
    },
  },
  teacherShard1: {
    allowedFields: [
      "id",
      "teacherId",
      "personId",
      "schoolId",
      "hireDate",
      "yearsExperience",
      "employmentStatus",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      teacherId: 1,
      personId: 1,
      schoolId: 1,
      yearsExperience: 0,
      employmentStatus: "Unknown Status",
      stateRegionId: 1,
    },
  },
  // Event tracking models
  // New lookup tables for database improvements
  statusType: {
    allowedFields: [
      "id",
      "statusName",
      "category",
      "description",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { statusName: "Unknown Status", category: "general", isActive: true },
    fieldMappings: { status_name: "statusName", is_active: "isActive" },
  },
  priorityType: {
    allowedFields: [
      "id",
      "priorityName",
      "level",
      "description",
      "color",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { priorityName: "Unknown Priority", level: 1, isActive: true },
    fieldMappings: { priority_name: "priorityName", is_active: "isActive" },
  },
  geographicReference: {
    allowedFields: [
      "referenceType",
      "referenceId",
      "name",
      "code",
      "parentId",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      referenceType: "unknown",
      referenceId: 1,
      name: "Unknown Reference",
      isActive: true,
    },
    fieldMappings: {
      reference_type: "referenceType",
      reference_id: "referenceId",
      parent_id: "parentId",
      is_active: "isActive",
    },
  },
  systemConfiguration: {
    allowedFields: [
      "configKey",
      "configValue",
      "dataType",
      "category",
      "description",
      "isEncrypted",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      configKey: "unknown.key",
      configValue: "default",
      dataType: "string",
      category: "system",
      isEncrypted: false,
      isActive: true,
    },
    fieldMappings: {
      config_key: "configKey",
      config_value: "configValue",
      data_type: "dataType",
      is_encrypted: "isEncrypted",
      is_active: "isActive",
    },
  },
  dataClassification: {
    allowedFields: [
      "classificationName",
      "level",
      "description",
      "retentionPeriod",
      "encryptionRequired",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      classificationName: "Unknown Classification",
      level: 1,
      encryptionRequired: false,
      isActive: true,
    },
    fieldMappings: {
      classification_name: "classificationName",
      retention_period: "retentionPeriod",
      encryption_required: "encryptionRequired",
      is_active: "isActive",
    },
  },
  auditLog: {
    allowedFields: [
      "tableName",
      "recordId",
      "operation",
      "oldValues",
      "newValues",
      "userId",
      "sessionId",
      "ipAddress",
      "userAgent",
      "classificationId",
      "stateRegionId",
      "createdAt",
    ],
    requiredDefaults: { tableName: "unknown_table", recordId: "unknown_id", operation: "UNKNOWN" },
    fieldMappings: {
      table_name: "tableName",
      record_id: "recordId",
      user_id: "userId",
      session_id: "sessionId",
      ip_address: "ipAddress",
      user_agent: "userAgent",
      classification_id: "classificationId",
      state_region_id: "stateRegionId",
    },
  },
  validationRule: {
    allowedFields: [
      "ruleName",
      "tableName",
      "columnName",
      "ruleType",
      "ruleValue",
      "errorMessage",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      ruleName: "Unknown Rule",
      tableName: "unknown_table",
      columnName: "unknown_column",
      ruleType: "unknown",
      ruleValue: "{}",
      errorMessage: "Validation failed",
      isActive: true,
    },
    fieldMappings: {
      rule_name: "ruleName",
      table_name: "tableName",
      column_name: "columnName",
      rule_type: "ruleType",
      rule_value: "ruleValue",
      error_message: "errorMessage",
      is_active: "isActive",
    },
  },
  eventType: {
    allowedFields: [
      "id",
      "typeName",
      "description",
      "category",
      "severity",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { typeName: "Unknown Event Type", isActive: true },
    fieldMappings: { type_name: "typeName", is_active: "isActive" },
  },
  eventShard1: {
    allowedFields: [
      "id",
      "eventName",
      "eventTypeId",
      "eventDate",
      "eventDocumentUrl",
      "eventWebpageUrl",
      "eventAiSummary",
      "eventDescription",
      "eventStatusId",
      "priorityId",
      "source",
      "verified",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      eventName: "Unknown Event",
      eventTypeId: 1,
      eventDate: new Date(),
      eventStatusId: 1,
      stateRegionId: 1,
      verified: false,
    },
    fieldMappings: {
      event_name: "eventName",
      event_type_id: "eventTypeId",
      event_date: "eventDate",
      event_document_url: "eventDocumentUrl",
      event_webpage_url: "eventWebpageUrl",
      event_ai_summary: "eventAiSummary",
      event_description: "eventDescription",
      event_status_id: "eventStatusId",
      priority_id: "priorityId",
      state_region_id: "stateRegionId",
    },
  },
  personEventShard1: {
    allowedFields: [
      "personId",
      "eventId",
      "relationshipType",
      "role",
      "notes",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { personId: 1, eventId: 1, relationshipType: "subject", stateRegionId: 1 },
    fieldMappings: {
      person_id: "personId",
      event_id: "eventId",
      relationship_type: "relationshipType",
      state_region_id: "stateRegionId",
    },
  },
  businessEventShard1: {
    allowedFields: [
      "businessId",
      "eventId",
      "relationshipType",
      "role",
      "notes",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { businessId: 1, eventId: 1, relationshipType: "subject", stateRegionId: 1 },
    fieldMappings: {
      business_id: "businessId",
      event_id: "eventId",
      relationship_type: "relationshipType",
      state_region_id: "stateRegionId",
    },
  },
  governmentEventShard1: {
    allowedFields: [
      "governmentEntityId",
      "eventId",
      "relationshipType",
      "role",
      "notes",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      governmentEntityId: 1,
      eventId: 1,
      relationshipType: "jurisdiction",
      stateRegionId: 1,
    },
    fieldMappings: {
      government_entity_id: "governmentEntityId",
      event_id: "eventId",
      relationship_type: "relationshipType",
      state_region_id: "stateRegionId",
    },
  },
  NGOEventShard1: {
    allowedFields: [
      "ngoId",
      "eventId",
      "relationshipType",
      "role",
      "notes",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: {
      ngoId: "Unknown-NGO",
      eventId: 1,
      relationshipType: "subject",
      stateRegionId: 1,
    },
    fieldMappings: {
      ngo_id: "ngoId",
      event_id: "eventId",
      relationship_type: "relationshipType",
      state_region_id: "stateRegionId",
    },
  },
  // Fiscal analysis models
  fiscalDataType: {
    allowedFields: ["typeName", "category", "description", "isActive", "createdAt", "updatedAt"],
    requiredDefaults: { isActive: true },
    fieldMappings: { type_name: "typeName", is_active: "isActive" },
  },
  fundType: {
    allowedFields: [
      "fundName",
      "fundCode",
      "category",
      "description",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { isActive: true },
    fieldMappings: { fund_name: "fundName", fund_code: "fundCode", is_active: "isActive" },
  },
  ACFRReport: {
    allowedFields: [
      "governmentEntityId",
      "fiscalYear",
      "reportDate",
      "reportType",
      "auditorName",
      "auditorOpinion",
      "reportUrl",
      "isExempt",
      "exemptionReason",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { isExempt: false, stateRegionId: 1 },
    fieldMappings: {
      government_entity_id: "governmentEntityId",
      fiscal_year: "fiscalYear",
      report_date: "reportDate",
      report_type: "reportType",
      auditor_name: "auditorName",
      auditor_opinion: "auditorOpinion",
      report_url: "reportUrl",
      is_exempt: "isExempt",
      exemption_reason: "exemptionReason",
      state_region_id: "stateRegionId",
    },
  },
  fiscalDataShard1: {
    allowedFields: [
      "acfrReportId",
      "fiscalDataTypeId",
      "fundTypeId",
      "amount",
      "description",
      "notes",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { stateRegionId: 1 },
    fieldMappings: {
      acfr_report_id: "acfrReportId",
      fiscal_data_type_id: "fiscalDataTypeId",
      fund_type_id: "fundTypeId",
      state_region_id: "stateRegionId",
    },
  },
  pensionPlan: {
    allowedFields: [
      "governmentEntityId",
      "planName",
      "planType",
      "planCode",
      "isActive",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { isActive: true, stateRegionId: 1 },
    fieldMappings: {
      government_entity_id: "governmentEntityId",
      plan_name: "planName",
      plan_type: "planType",
      plan_code: "planCode",
      is_active: "isActive",
      state_region_id: "stateRegionId",
    },
  },
  pensionDataShard1: {
    allowedFields: [
      "pensionPlanId",
      "acfrReportId",
      "totalPensionLiability",
      "fiduciaryNetPosition",
      "netPensionLiability",
      "actuariallyRequiredContribution",
      "actualContribution",
      "normalCost",
      "unfundedActuarialAccruedLiability",
      "fundedRatio",
      "discountRate",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { stateRegionId: 1 },
    fieldMappings: {
      pension_plan_id: "pensionPlanId",
      acfr_report_id: "acfrReportId",
      total_pension_liability: "totalPensionLiability",
      fiduciary_net_position: "fiduciaryNetPosition",
      net_pension_liability: "netPensionLiability",
      actuarially_required_contribution: "actuariallyRequiredContribution",
      actual_contribution: "actualContribution",
      normal_cost: "normalCost",
      unfunded_actuarial_accrued_liability: "unfundedActuarialAccruedLiability",
      funded_ratio: "fundedRatio",
      discount_rate: "discountRate",
      state_region_id: "stateRegionId",
    },
  },
  OPEBDataShard1: {
    allowedFields: [
      "governmentEntityId",
      "acfrReportId",
      "totalOPEBLiability",
      "opebFiduciaryNetPosition",
      "netOPEBLiability",
      "opebFundingRatio",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { stateRegionId: 1 },
    fieldMappings: {
      government_entity_id: "governmentEntityId",
      acfr_report_id: "acfrReportId",
      total_opeb_liability: "totalOPEBLiability",
      opeb_fiduciary_net_position: "opebFiduciaryNetPosition",
      net_opeb_liability: "netOPEBLiability",
      opeb_funding_ratio: "opebFundingRatio",
      state_region_id: "stateRegionId",
    },
  },
  fiscalHealthScore: {
    allowedFields: [
      "governmentEntityId",
      "fiscalYear",
      "generalFundReserveScore",
      "debtBurdenScore",
      "liquidityPositionScore",
      "revenueTrendScore",
      "pensionCostsScore",
      "pensionFundingScore",
      "pensionObligationsScore",
      "opebObligationScore",
      "opebFundingScore",
      "netWorthScore",
      "overallScore",
      "scoreDate",
      "calculationMethod",
      "stateRegionId",
      "createdAt",
      "updatedAt",
    ],
    requiredDefaults: { stateRegionId: 1 },
    fieldMappings: {
      government_entity_id: "governmentEntityId",
      fiscal_year: "fiscalYear",
      general_fund_reserve_score: "generalFundReserveScore",
      debt_burden_score: "debtBurdenScore",
      liquidity_position_score: "liquidityPositionScore",
      revenue_trend_score: "revenueTrendScore",
      pension_costs_score: "pensionCostsScore",
      pension_funding_score: "pensionFundingScore",
      pension_obligations_score: "pensionObligationsScore",
      opeb_obligation_score: "opebObligationScore",
      opeb_funding_score: "opebFundingScore",
      net_worth_score: "netWorthScore",
      overall_score: "overallScore",
      score_date: "scoreDate",
      calculation_method: "calculationMethod",
      state_region_id: "stateRegionId",
    },
  },
  // HOA Models
  homeOwnerAssociation: {
    allowedFields: [
      "name",
      "dateEstablished",
      "locationId",
      "website",
      "administrationSoftware",
      "managementStructure",
      "ageRestrictions",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      date_established: "dateEstablished",
      location_id: "locationId",
      administration_software: "administrationSoftware",
      management_structure: "managementStructure",
      age_restrictions: "ageRestrictions",
    },
  },
  hOABoardMember: {
    allowedFields: [
      "hoaId",
      "prefix",
      "firstName",
      "lastName",
      "position",
      "termStart",
      "termEnd",
      "contactEmail",
      "contactPhone",
      "isCurrent",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      first_name: "firstName",
      last_name: "lastName",
      term_start: "termStart",
      term_end: "termEnd",
      contact_email: "contactEmail",
      contact_phone: "contactPhone",
      is_current: "isCurrent",
    },
  },
  hOAFinancialRecord: {
    allowedFields: [
      "hoaId",
      "recordType",
      "effectiveDate",
      "description",
      "documentUrl",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      record_type: "recordType",
      effective_date: "effectiveDate",
      document_url: "documentUrl",
    },
  },
  hOAInvoice: {
    allowedFields: [
      "hoaId",
      "invoiceNumber",
      "invoiceDate",
      "invoiceAmount",
      "unpaidInvoiceAmount",
      "costPaid",
      "dueDate",
      "paidDate",
      "vendorName",
      "vendorBusinessId",
      "serviceType",
      "serviceDescription",
      "authorizingBoardMemberId",
      "authorizingManagementCompanyId",
      "financialRecordId",
      "description",
      "invoiceDocumentUrl",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      invoice_number: "invoiceNumber",
      invoice_date: "invoiceDate",
      invoice_amount: "invoiceAmount",
      unpaid_invoice_amount: "unpaidInvoiceAmount",
      cost_paid: "costPaid",
      due_date: "dueDate",
      paid_date: "paidDate",
      vendor_name: "vendorName",
      vendor_business_id: "vendorBusinessId",
      service_type: "serviceType",
      service_description: "serviceDescription",
      authorizing_board_member_id: "authorizingBoardMemberId",
      authorizing_management_company_id: "authorizingManagementCompanyId",
      financial_record_id: "financialRecordId",
      invoice_document_url: "invoiceDocumentUrl",
    },
  },
  hOAFeeHistory: {
    allowedFields: [
      "hoaId",
      "feeType",
      "amount",
      "effectiveDate",
      "reason",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      fee_type: "feeType",
      effective_date: "effectiveDate",
    },
  },
  hOAGoverningDocument: {
    allowedFields: [
      "hoaId",
      "documentType",
      "title",
      "version",
      "effectiveDate",
      "documentUrl",
      "description",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      document_type: "documentType",
      effective_date: "effectiveDate",
      document_url: "documentUrl",
    },
  },
  hOAAmenity: {
    allowedFields: [
      "hoaId",
      "amenityName",
      "description",
      "maintenanceResponsibility",
      "accessRestrictions",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      amenity_name: "amenityName",
      maintenance_responsibility: "maintenanceResponsibility",
      access_restrictions: "accessRestrictions",
    },
  },
  hOALegalRecord: {
    allowedFields: [
      "hoaId",
      "recordType",
      "caseNumber",
      "jurisdiction",
      "description",
      "status",
      "dateFiled",
      "resolutionDate",
      "legalDocumentUrl",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      record_type: "recordType",
      case_number: "caseNumber",
      date_filed: "dateFiled",
      resolution_date: "resolutionDate",
      legal_document_url: "legalDocumentUrl",
    },
  },
  hOAAssessment: {
    allowedFields: [
      "hoaId",
      "assessmentType",
      "amount",
      "purpose",
      "dueDate",
      "assessmentDocumentUrl",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      assessment_type: "assessmentType",
      due_date: "dueDate",
      assessment_document_url: "assessmentDocumentUrl",
    },
  },
  hOAMeeting: {
    allowedFields: [
      "hoaId",
      "meetingDateTime",
      "meetingType",
      "meetingDocumentUrl",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      meeting_date_time: "meetingDateTime",
      meeting_type: "meetingType",
      meeting_document_url: "meetingDocumentUrl",
    },
  },
  hOAManagementCompany: {
    allowedFields: [
      "hoaId",
      "managementCompanyId",
      "contractStartDate",
      "contractEndDate",
      "isActive",
      "contractAmount",
      "contractType",
      "contractDocumentUrl",
      "terminationReason",
      "notes",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      hoa_id: "hoaId",
      management_company_id: "managementCompanyId",
      contract_start_date: "contractStartDate",
      contract_end_date: "contractEndDate",
      is_active: "isActive",
      contract_amount: "contractAmount",
      contract_type: "contractType",
      contract_document_url: "contractDocumentUrl",
      termination_reason: "terminationReason",
    },
  },
  subdivision: {
    allowedFields: ["hoaId", "name", "dateCreated", "homeBuilderId", "createdAt", "updatedAt"],
    fieldMappings: {
      hoa_id: "hoaId",
      date_created: "dateCreated",
      home_builder_id: "homeBuilderId",
    },
  },
  homeBuilder: {
    allowedFields: ["name", "website", "dateFormed", "locationId", "createdAt", "updatedAt"],
    fieldMappings: {
      date_formed: "dateFormed",
      location_id: "locationId",
    },
  },
  realtor: {
    allowedFields: [
      "userId",
      "realtyAgency",
      "specialization",
      "locationId",
      "createdAt",
      "updatedAt",
    ],
    fieldMappings: {
      user_id: "userId",
      realty_agency: "realtyAgency",
      location_id: "locationId",
    },
  },
};
