const jobRoles = [
  "MIS/IT - Data Center",
  "MIS/IT- Operations",
  "MIS/IT - Security",
  "MIS/IT - Storage",
  "MIS/IT - Telecom",
  "Executive Management",
  "Marketing Manager",
  "Finance/Accounting",
  "Network Management",
  "Operations/Administration",
  "Operations/Administration - Security",
  "Operations Manager",
  "Other",
  "Manufacturing",
  "Marketing/PR/Advertising",
  "Sales",
  "Sales Manager",
  "Technical Support",
  "Training/Education",
  "Purchasing/Procurement",
  "Research/Development",
  "Account Manager",
  "Administrator",
  "Business Development",
  "Consultant/Contractor",
  "Customer Service",
  "E-Commerce",
  "Engineering",
  "HR/Recruitment",
  "Information Technology",
  "Journalism",
  "Legal",
  "Logistics",
  "MIS/IT",
  "MIS/IT - Applications Dev",
  "System / Sales Engineer  ",
];

export default jobRoles;
